#!/bin/bash
if [[ ! -d "/etc/apt/keyrings" ]]; then
   install -m 0755 -d /etc/apt/keyrings
fi

if [[ ! -e "/etc/apt/sources.list.d/docker.list" ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
fi
