#!/bin/bash

if [[ ! $(docker --version) ]]; then
    #https://docs.docker.com/engine/install/ubuntu/
    echo "Installing docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove -y $pkg; done
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    usermod -aG docker $SUDO_USER
fi
